services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: attendance_mvp_db
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_pass
    ports:
      - "5432:5432"
    volumes:
      - attendance_pg_data:/var/lib/postgresql/data

volumes:
  attendance_pg_data: